apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stockquote-ns
  labels:
    app: sq-deploy
  name: sq-deploy
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: sq-pod
  template:
    metadata:
      labels:
        app: sq-pod
    spec:
      containers:
      - image: damans227/stockquote-webapp:v1
        name: stockquote-webapp

